spring:
  application:
    name: remind-me-server

  # Database 설정 (Docker MySQL 기준)
  datasource:
    url: jdbc:mysql://localhost:3306/remindme?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update # 개발 초기 단계이므로 update 사용
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379

# Swagger (SpringDoc) 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: asc
  api-docs:
    path: /api-docs

  # 최소 32자 이상의 랜덤 문자열을 사용하세요
  jwt:
    secret: vms70639fd880bc60568d0301191edc0c115267483c56f7657c7674245e8f926
    expiration: 86400000 # 24시간
